export const ACCOUNT_CREDIT = 'ACCOUNT_CREDIT';
export const ACCOUNT_DEBIT = 'ACCOUNT_DEBIT';
export const ACCOUNT_DELETE_CC = 'ACCOUNT_DELETE_CC';
export const ACCOUNT_DELETE_IBAN = 'ACCOUNT_DELETE_IBAN';
export const ACCOUNT_GET_ALL = 'ACCOUNT_GET_ALL';
export const ACCOUNT_GET_OPERATIONS = 'ACCOUNT_GET_OPERATIONS';
export const ACCOUNT_UPDATE_CC = 'ACCOUNT_UPDATE_CC';
export const ACCOUNT_UPDATE_IBAN = 'ACCOUNT_UPDATE_IBAN';

export const ALERTS_DELETE_DISPLAYED = 'ALERTS_DELETE_DISPLAYED';

export const CARPOOL_ACCEPT = 'CARPOOL_ACCEPT';
export const CARPOOL_REJECT = 'CARPOOL_REJECT';
export const CARPOOL_CLAIM = 'CARPOOL_CLAIM';

export const COMMUNITIES_GET_ALL_PUBLIC = 'COMMUNITIES_GET_ALL_PUBLIC';
export const COMMUNITIES_GET_ALL = 'COMMUNITIES_GET_ALL';
export const COMMUNITIES_GET_ALL_PENDING = 'COMMUNITIES_GET_ALL_PENDING';
export const COMMUNITIES_SUBSCRIBE = 'COMMUNITIES_SUBSCRIBE';

export const DOCS_OPEN_CHARTER = 'DOCS_OPEN_CHARTER';
export const DOCS_OPEN_TERMS = 'DOCS_OPEN_TERMS';
export const DOCS_OPEN_PRIVACY = 'DOCS_OPEN_PRIVACY';
export const DOCS_CLOSE = 'DOCS_CLOSE';

export const HELP_CLOSE = 'HELP_CLOSE';
export const HELP_OPEN = 'HELP_OPEN';

export const MENU_CLOSE = 'MENU_CLOSE';
export const MENU_OPEN = 'MENU_OPEN';

export const MESSAGES_GET_ROOMS = 'MESSAGES_GET_ROOMS';
export const MESSAGES_OPEN_CHAT_ROOM = 'MESSAGES_OPEN_CHAT_ROOM';

export const MOVE_GET_DETAILS = 'MOVE_GET_DETAILS';
export const MOVE_GET_SOLUTIONS = 'MOVE_GET_SOLUTIONS';
export const MOVE_DELETE_ONE = 'MOVE_DELETE_ONE';
export const MOVE_SELECT_SOLUTION = 'MOVE_SELECT_SOLUTION';
export const MOVE_UNSELECT_SOLUTION = 'MOVE_UNSELECT_SOLUTION';

export const NOTIFICATIONS_PUSH_SUBSCRIBE = 'NOTIFICATIONS_SUBSCRIBE';
export const NOTIFICATIONS_PUSH_UNSUBSCRIBE = 'NOTIFICATIONS_UNSUBSCRIBE';
export const NOTIFICATIONS_PUSH_RECEIVE = 'NOTIFICATIONS_RECEIVE';
export const NOTIFICATIONS_ACTION = 'NOTIFICATIONS_ACTION';

export const PLACES_ADD_ONE = 'PLACES_ADD_ONE';
export const PLACES_GET_ALL = 'PLACES_GET_ALL';
export const PLACES_DELETE_ONE = 'PLACES_DELETE_ONE';

export const PREFERENCES_GET = 'PREFERENCES_GET';
export const PREFERENCES_UPDATE = 'PREFERENCES_UPDATE';

export const PUBLIC_USER_GET = 'PUBLIC_USER_GET';

export const MOVES_LOAD_NEXT_MOVES = 'MOVES_LOAD_NEXT_MOVES';
export const MOVES_RESET_LIST = 'MOVES_RESET_LIST';

export const TRIPS_ADD_ONE = 'TRIPS_ADD_ONE';
export const TRIPS_DELETE_ONE = 'TRIPS_DELETE_ONE';
export const TRIPS_GET_ALL = 'TRIPS_GET_ALL';
export const TRIPS_UPDATE_ONE = 'TRIPS_UPDATE_ONE';

export const TRIPCREATION_SET_ORIGIN = 'TRIPCREATION_SET_ORIGIN';
export const TRIPCREATION_SET_DESTINATION = 'TRIPCREATION_SET_DESTINATION';
export const TRIPCREATION_SET_COMMUNITY = 'TRIPCREATION_SET_COMMUNITY';
export const TRIPCREATION_SET_SCHEDULES = 'TRIPCREATION_SET_SCHEDULES';
export const TRIPCREATION_SET_DRIVE_DEF = 'TRIPCREATION_SET_DRIVE_DEF';
export const TRIPCREATION_SET_TRIP = 'TRIPCREATION_SET_TRIP';
export const TRIPCREATION_SET_STEP = 'TRIPCREATION_SET_STEP';
export const TRIPCREATION_DELETE_TRIP = 'TRIPCREATION_DELETE_TRIP';
export const TRIPCREATION_ADD_DRIVE = 'TRIPCREATION_ADD_DRIVE';
export const TRIPCREATION_DELETE_DRIVE = 'TRIPCREATION_DELETE_DRIVE';
export const TRIPCREATION_ADD_RETURN_DRIVE = 'TRIPCREATION_ADD_RETURN_DRIVE';
export const TRIPCREATION_DELETE_RETURN_DRIVE =
  'TRIPCREATION_DELETE_RETURN_DRIVE';
export const TRIPCREATION_RESET = 'TRIPCREATION_RESET';

export const USER_CHANGE_LANGUAGE = 'USER_CHANGE_LANGUAGE';
export const USER_CHANGE_LANGUAGE_FULFILLED = 'USER_CHANGE_LANGUAGE_FULFILLED';
export const USER_CREATE_PASSWORD = 'USER_CREATE_PASSWORD';
export const USER_CREATE_PROFILE = 'USER_CREATE_PROFILE';
export const USER_DEACTIVATE = 'USER_DEACTIVATE';
export const USER_FORGOT_PASSWORD = 'USER_FORGOT_PASSWORD';
export const USER_GET_PRIVATE = 'USER_GET_PRIVATE';
export const USER_PHOTO_UPDATE = 'USER_PHOTO_UPDATE';
export const USER_PICTURE_UPDATE = 'USER_PICTURE_UPDATE';
export const USER_PICTURE_DELETE = 'USER_PICTURE_DELETE';
export const USER_PHOTO_DELETE = 'USER_PHOTO_DELETE';
export const USER_SAVE_EMAIL = 'USER_SAVE_EMAIL';
export const USER_SAVE_REDIRECT = 'USER_SAVE_REDIRECT';
export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNIN_FULFILLED = 'USER_SIGNIN_FULFILLED';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_PREFERENCE = 'USER_UPDATE_PREFERENCE';

export const VEHICLES_ADD_ONE = 'VEHICLES_ADD_ONE';
export const VEHICLES_DELETE_ONE = 'VEHICLES_DELETE_ONE';
export const VEHICLES_GET_ALL = 'VEHICLES_GET_ALL';
export const VEHICLES_PICTURE_UPDATE = 'VEHICLES_PICTURE_UPDATE';
export const VEHICLES_PICTURE_DELETE = 'VEHICLES_PICTURE_DELETE';
export const VEHICLES_PHOTO_UPDATE = 'VEHICLES_PHOTO_UPDATE';
export const VEHICLES_PHOTO_DELETE = 'VEHICLES_PHOTO_DELETE';
export const VEHICLES_UPDATE_ONE = 'VEHICLES_UPDATE_ONE';
